version: "2"
plugins:
  standard:
    channels:
     stable: codeclimate/codeclimate-standard
     beta: codeclimate/codeclimate-standard
    description: Standard static analysis tool.
  structure:
    channels:
      stable: codeclimate/codeclimate-structure
    description: Performs structural checks on code.
  duplication:
    enabled: true
  fixme:
    enabled: true
  cppcheck:
    enabled: true
    config:
      check: all
      standard: "cpp17"
      library: googletest
exclude_patterns:
  - src/OgreXML/*
