version: "2"
plugins:
  duplication:
    enabled: true
  fixme:
    enabled: true
  cppcheck:
    enabled: true
    config:
      check: all
      standard: "cpp17"
      library: googletest
exclude_patterns:
  - src/OgreXML/*
