version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 10
  identical-code:
    enabled: true
    config:
      threshold: 10
plugins:
  standard:
    enabled: true
  structure:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  cppcheck:
    enabled: true
    config:
      check: all
      standard: "cpp17"
      library: googletest
exclude_patterns:
  - "src/OgreXML/"
  - "src/dependencies/ogre-procedural/library/src/"
  - "src/UnitTests_autogen/**/*.cpp"
  - "*_autogen*"
  - "src/dependencies/"
  - "**/CMakeFiles/*"
  - "_deps/"
  - "ui_files/"
  - "moc_*"
  - "media/"
  - "lib/"
  - "bin/"
  - "cfg/"
  - "*.cc"
  - "*.md"
  - "*.in"
  - "*.yml"
  - "*.cmake"
  - "*.txt"
  - "makefile"
