version: "2"
plugins:
  cppcheck:
    enabled: true
    config:
      standard: "cpp17"
  cpplint:
    enabled: true
    config:
      extensions: "cpp,hpp"
  clang-tidy:
    enabled: true
    config:
      checks: "-*,modernize-*"
  iwyu:
    enabled: true
exclude_paths:
  - src/OgreXML
