/* This file is autogenerated, do not edit*/
#include "moc_about.cpp"
#include "moc_addprimitives.cpp"
#include "moc_mainwindow.cpp"
#include "moc_material.cpp"
#include "moc_materialeditor.cpp"
