#!/usr/bin/env python3
"""Convert MediaPipe Face/Pose Landmarker TFLite models to ONNX, with parity proof (#870).

ONE-TIME, OFFLINE developer tool — NOT shipped with the app, and the app never
runs Python. The app runs the resulting .onnx files in C++ via ONNX Runtime
(src/Mocap/FaceCapPredictor.cpp / PoseIK pipeline), downloading them on first
use to AppData/ai_models/mocap/{face,pose}/.

WHAT IT PRODUCES (in --out-dir, default .mocap_work/out)
  face/face_detector.onnx      BlazeFace short-range:  in [1,128,128,3] RGB in [-1,1]
                               out regressors [1,896,16], classificators [1,896,1]
  face/face_landmarks.onnx     Face Mesh V2:           in [N,256,256,3] RGB in [0,1]
                               out [N,1,1,1434] (478 xyz landmarks, px in 256-space),
                                   [N,1,1,1] face-presence logit, [N,1] (unused aux)
  face/face_blendshapes.onnx   MLP-Mixer blendshapes:  in [1,146,2] (x*W, y*H pixel coords
                               of the 146-landmark subset), out [52] scores in [0,1]
  pose/pose_detector.onnx      BlazePose detector:     in [1,224,224,3] RGB in [-1,1]
                               out [1,2254,12], [1,2254,1]
  pose/pose_landmarks.onnx     BlazePose full:         in [1,256,256,3] RGB in [0,1]
                               out [1,195] (39 x,y,z,visibility,presence in 256-space),
                                   [1,1] pose-presence, [1,256,256,1] seg, [1,64,64,39] heatmap,
                                   [1,117] world landmarks (39 xyz, metres, hip-centred)

DATA + LICENSE
  All five models are Google MediaPipe models, Apache-2.0 (code AND weights) —
  see THIRD_PARTY_AI_MODELS.md. Downloaded .task bundles are zip files
  containing the TFLite graphs this script converts.

CONVERSION NOTES (discovered empirically, kept for reproducibility)
  * tf2onnx 1.17.0 + tensorflow 2.21 + python 3.12 work.
  * pose_detector.tflite ships fp16 block-SPARSE weights behind DENSIFY ops,
    which tf2onnx cannot parse. densify_tflite() runs the TFLite interpreter
    with experimental_preserve_all_tensors, captures each DENSIFY output, and
    rewrites the flatbuffer with dense buffers + the DENSIFY ops removed.
  * face_blendshapes.tflite converts, but tf2onnx's post-conversion optimizer
    produces a graph onnxruntime rejects (transpose optimizer breaks a
    LayerNorm Mul). We convert that model with optimizers DISABLED.

PRE/POST-PROCESSING CONTRACT (the spec Slice C implements in C++; also in
docs/MOCAP_SPIKE.md):
  * Detector input: letterbox (keep aspect, centre, pad both sides) to the
    input size, RGB, normalize to [-1,1] ((v/255)*2-1).
  * Face SSD anchors: 4 layers, strides [8,16,16,16], 2 anchors on the two
    16x16 layers' merged... generated by gen_ssd_anchors() below (896 anchors,
    all 1.0 aspect, fixed size). Pose: 5 layers, strides [8,16,32,32,32]
    (2254 anchors). Decode: offsets / input_size scaled around anchor centres;
    score = sigmoid(clip(raw, -100, 100)); weighted NMS at IoU 0.3.
  * Face ROI: rotation from detector keypoint 0 (right eye) -> 1 (left eye),
    target angle 0; rect = detection box made square-long then scaled 1.5x.
  * Pose ROI: centre = detector keypoint 0 (mid-hip), radius = |kp1-kp0|,
    box = 2*radius square, rotation target angle 90 deg, then scaled 1.25x.
  * Landmark crop: rotated rect resampled to 256x256, RGB in [0,1].
  * Landmark decode: xyz / 256 -> normalized crop coords -> rotate/scale back
    through the ROI transform (landmark projection); z scaled by rect w.
  * Blendshape input: the 146-subset landmark (x*imgW, y*imgH) pixel coords.
  * Pose world landmarks: rotate x,y by the ROI rotation only (no scale).
  * Head pose: weighted Umeyama/Kabsch fit of the 468 canonical-face-model
    vertices (Procrustes basis weights) against screen landmarks
    (x*W, -y*H, -z*W); rotation kept, scale discarded. This intentionally
    replaces MediaPipe's perspective geometry pipeline; parity vs its
    facial_transformation_matrix is reported in degrees (a few deg is fine).

USAGE (offline, in a venv with mediapipe tensorflow tf2onnx onnx onnxruntime pillow):
    python scripts/export-facecap-onnx.py \
        --face-task .mocap_work/models/face_landmarker.task \
        --pose-task .mocap_work/models/pose_landmarker_full.task \
        --images .mocap_work/images --out-dir .mocap_work/out
"""

import argparse
import json
import math
import os
import shutil
import sys
import zipfile

import numpy as np

# ---------------------------------------------------------------------------
# constants extracted from MediaPipe source (Apache-2.0), pinned here so the
# C++ side and this script share one source of truth (also emitted to JSON).
# ---------------------------------------------------------------------------

# mediapipe/tasks/cc/vision/face_landmarker/face_blendshapes_graph.cc
BLENDSHAPE_LANDMARK_SUBSET = [
    0, 1, 4, 5, 6, 7, 8, 10, 13, 14, 17, 21, 33, 37, 39,
    40, 46, 52, 53, 54, 55, 58, 61, 63, 65, 66, 67, 70, 78, 80,
    81, 82, 84, 87, 88, 91, 93, 95, 103, 105, 107, 109, 127, 132, 133,
    136, 144, 145, 146, 148, 149, 150, 152, 153, 154, 155, 157, 158, 159, 160,
    161, 162, 163, 168, 172, 173, 176, 178, 181, 185, 191, 195, 197, 234, 246,
    249, 251, 263, 267, 269, 270, 276, 282, 283, 284, 285, 288, 291, 293, 295,
    296, 297, 300, 308, 310, 311, 312, 314, 317, 318, 321, 323, 324, 332, 334,
    336, 338, 356, 361, 362, 365, 373, 374, 375, 377, 378, 379, 380, 381, 382,
    384, 385, 386, 387, 388, 389, 390, 397, 398, 400, 402, 405, 409, 415, 454,
    466, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
]

BLENDSHAPE_NAMES = [
    "_neutral", "browDownLeft", "browDownRight", "browInnerUp",
    "browOuterUpLeft", "browOuterUpRight", "cheekPuff", "cheekSquintLeft",
    "cheekSquintRight", "eyeBlinkLeft", "eyeBlinkRight", "eyeLookDownLeft",
    "eyeLookDownRight", "eyeLookInLeft", "eyeLookInRight", "eyeLookOutLeft",
    "eyeLookOutRight", "eyeLookUpLeft", "eyeLookUpRight", "eyeSquintLeft",
    "eyeSquintRight", "eyeWideLeft", "eyeWideRight", "jawForward", "jawLeft",
    "jawOpen", "jawRight", "mouthClose", "mouthDimpleLeft", "mouthDimpleRight",
    "mouthFrownLeft", "mouthFrownRight", "mouthFunnel", "mouthLeft",
    "mouthLowerDownLeft", "mouthLowerDownRight", "mouthPressLeft",
    "mouthPressRight", "mouthPucker", "mouthRight", "mouthRollLower",
    "mouthRollUpper", "mouthShrugLower", "mouthShrugUpper", "mouthSmileLeft",
    "mouthSmileRight", "mouthStretchLeft", "mouthStretchRight",
    "mouthUpperUpLeft", "mouthUpperUpRight", "noseSneerLeft", "noseSneerRight",
]

# MediaPipe pose landmark index -> body part (33 real landmarks; the model
# emits 39, the last 6 are auxiliary and dropped).
POSE_LANDMARK_NAMES = [
    "nose", "left_eye_inner", "left_eye", "left_eye_outer", "right_eye_inner",
    "right_eye", "right_eye_outer", "left_ear", "right_ear", "mouth_left",
    "mouth_right", "left_shoulder", "right_shoulder", "left_elbow",
    "right_elbow", "left_wrist", "right_wrist", "left_pinky", "right_pinky",
    "left_index", "right_index", "left_thumb", "right_thumb", "left_hip",
    "right_hip", "left_knee", "right_knee", "left_ankle", "right_ankle",
    "left_heel", "right_heel", "left_foot_index", "right_foot_index",
]


# ---------------------------------------------------------------------------
# TFLite -> ONNX conversion
# ---------------------------------------------------------------------------

def densify_tflite(src, dst):
    """Rewrite a TFLite flatbuffer with all DENSIFY'd sparse constants dense.

    tf2onnx cannot parse TFLite block-sparse tensors. The TFLite interpreter
    can (XNNPACK densifies at prepare time), so we run it once with
    experimental_preserve_all_tensors, read back each DENSIFY output, store it
    as a dense buffer on the op's input tensor, rewire consumers and drop the
    DENSIFY ops. Returns the number of ops removed (0 = no rewrite needed).
    """
    import tensorflow as tf
    from tensorflow.lite.tools import flatbuffer_utils
    from tensorflow.lite.python import schema_py_generated as schema

    names = {v: k for k, v in schema.BuiltinOperator.__dict__.items()
             if isinstance(v, int)}
    model = flatbuffer_utils.read_model(src)
    sg = model.subgraphs[0]

    def is_densify(op):
        code = model.operatorCodes[op.opcodeIndex]
        bc = max(code.builtinCode, getattr(code, "deprecatedBuiltinCode", 0))
        return names.get(bc) == "DENSIFY"

    if not any(is_densify(op) for op in sg.operators):
        shutil.copyfile(src, dst)
        return 0

    interp = tf.lite.Interpreter(
        model_path=src,
        experimental_preserve_all_tensors=True,
        # XNNPACK folds DENSIFY away and get_tensor() then reads garbage —
        # run pure-builtin so every intermediate tensor is materialized.
        experimental_op_resolver_type=tf.lite.experimental.OpResolverType
        .BUILTIN_WITHOUT_DEFAULT_DELEGATES)
    interp.allocate_tensors()
    inp = interp.get_input_details()[0]
    interp.set_tensor(inp["index"], np.zeros(inp["shape"], dtype=inp["dtype"]))
    interp.invoke()

    kept = []
    removed = 0
    for op in sg.operators:
        if not is_densify(op):
            kept.append(op)
            continue
        removed += 1
        ti, to = int(op.inputs[0]), int(op.outputs[0])
        dense = interp.get_tensor(to)
        tensor = sg.tensors[ti]
        # type 1 == FLOAT16 in the tflite schema; keep the storage dtype.
        data = np.ascontiguousarray(
            dense.astype(np.float16 if tensor.type == 1 else dense.dtype)
        ).tobytes()
        buf = schema.BufferT()
        buf.data = np.frombuffer(data, dtype=np.uint8)
        model.buffers.append(buf)
        tensor.buffer = len(model.buffers) - 1
        tensor.sparsity = None
        for other in sg.operators:
            if other is not op:
                other.inputs = [ti if int(x) == to else int(x)
                                for x in other.inputs]
    sg.operators = kept
    flatbuffer_utils.write_model(model, dst)
    return removed


def convert_tflite_to_onnx(tflite_path, onnx_path, optimize=True):
    """tf2onnx conversion via the python API so the optimizer can be skipped."""
    import onnx
    from tf2onnx.tfonnx import process_tf_graph
    from tf2onnx import optimizer as tf2onnx_optimizer

    g = process_tf_graph(None, opset=18, tflite_path=tflite_path)
    if optimize:
        g = tf2onnx_optimizer.optimize_graph(g, catch_errors=True)
    model_proto = g.make_model(os.path.basename(onnx_path))
    onnx.save(model_proto, onnx_path)


def ort_session(path):
    import onnxruntime as ort
    return ort.InferenceSession(path, providers=["CPUExecutionProvider"])


def convert_with_fallback(tflite_path, onnx_path):
    """Convert; if onnxruntime rejects the optimized graph, retry unoptimized."""
    work = tflite_path
    dense = onnx_path + ".dense.tflite"
    removed = densify_tflite(tflite_path, dense)
    if removed:
        print(f"    densified {removed} sparse tensors")
        work = dense
    try:
        convert_tflite_to_onnx(work, onnx_path, optimize=True)
        ort_session(onnx_path)
        mode = "optimized"
    except Exception as exc:  # noqa: BLE001 - any ORT load failure
        print(f"    optimized graph rejected ({type(exc).__name__}); "
              "retrying with tf2onnx optimizers disabled")
        convert_tflite_to_onnx(work, onnx_path, optimize=False)
        ort_session(onnx_path)
        mode = "unoptimized"
    if os.path.exists(dense):
        os.remove(dense)
    print(f"    -> {onnx_path} ({mode}, "
          f"{os.path.getsize(onnx_path) / 1e6:.1f} MB)")


# ---------------------------------------------------------------------------
# shared pipeline math (this is the contract Slice C reimplements in C++)
# ---------------------------------------------------------------------------

def letterbox(img, size):
    """Keep-aspect centre letterbox to size x size (BORDER_ZERO, plain
    bilinear — cv2, NOT an antialiased resampler; matches MediaPipe's
    ImageToTensor). Returns (uint8 HxWx3 array, pad).

    pad = (pad_x, pad_y, fx, fy): normalized padding on each leading side of
    the letterboxed square and the fraction of the square the image occupies.
    """
    import cv2
    arr = np.asarray(img)
    h, w = arr.shape[:2]
    s = size / max(w, h)
    ox, oy = (size - w * s) / 2.0, (size - h * s) / 2.0
    m = np.array([[s, 0, ox], [0, s, oy]], dtype=np.float64)
    out = cv2.warpAffine(arr, m, (size, size), flags=cv2.INTER_LINEAR,
                         borderMode=cv2.BORDER_CONSTANT, borderValue=0)
    return out, (ox / size, oy / size, w * s / size, h * s / size)


def unletterbox_points(pts, pad):
    """Map normalized letterbox-square coords -> normalized original coords."""
    pad_x, pad_y, fx, fy = pad
    out = pts.copy()
    out[..., 0] = (pts[..., 0] - pad_x) / fx
    out[..., 1] = (pts[..., 1] - pad_y) / fy
    return out


def gen_ssd_anchors(input_size, strides, min_scale=0.1484375, max_scale=0.75,
                    anchor_offset=0.5, interpolated_scale_aspect_ratio=1.0):
    """MediaPipe SsdAnchorsCalculator with aspect_ratios=[1.0], fixed size."""
    def scale_for(i, n):
        if n == 1:
            return (min_scale + max_scale) * 0.5
        return min_scale + (max_scale - min_scale) * i / (n - 1)

    anchors = []
    n = len(strides)
    layer = 0
    while layer < n:
        # merge consecutive identical strides into one layer
        last = layer
        scales = []
        while last < n and strides[last] == strides[layer]:
            scales.append(scale_for(last, n))
            if interpolated_scale_aspect_ratio > 0.0:
                nxt = 1.0 if last == n - 1 else scale_for(last + 1, n)
                scales.append(math.sqrt(scales[-1] * nxt))
            last += 1
        stride = strides[layer]
        fm = int(math.ceil(input_size / stride))
        for y in range(fm):
            for x in range(fm):
                for _ in scales:
                    anchors.append(((x + anchor_offset) / fm,
                                    (y + anchor_offset) / fm))
        layer = last
    return np.array(anchors, dtype=np.float32)


def decode_detections(raw_boxes, raw_scores, anchors, input_size, num_keypoints,
                      min_score=0.5):
    """MediaPipe TensorsToDetections: fixed anchor size, no box flip."""
    scores = sigmoid(raw_scores[..., 0])
    keep = scores >= min_score
    boxes = raw_boxes[keep]
    scores = scores[keep]
    anc = anchors[keep]
    if boxes.shape[0] == 0:
        return []
    cx = boxes[:, 0] / input_size + anc[:, 0]
    cy = boxes[:, 1] / input_size + anc[:, 1]
    w = boxes[:, 2] / input_size
    h = boxes[:, 3] / input_size
    kps = np.stack([boxes[:, 4 + 2 * k:6 + 2 * k] / input_size + anc
                    for k in range(num_keypoints)], axis=1)
    dets = []
    for i in range(boxes.shape[0]):
        dets.append({
            "score": float(scores[i]),
            "box": (float(cx[i] - w[i] / 2), float(cy[i] - h[i] / 2),
                    float(w[i]), float(h[i])),
            "keypoints": kps[i].astype(float),
        })
    return weighted_nms(dets)


def weighted_nms(dets, min_suppression_threshold=0.3):
    """MediaPipe weighted non-max-suppression."""
    def iou(a, b):
        ax, ay, aw, ah = a
        bx, by, bw, bh = b
        x1, y1 = max(ax, bx), max(ay, by)
        x2, y2 = min(ax + aw, bx + bw), min(ay + ah, by + bh)
        inter = max(0.0, x2 - x1) * max(0.0, y2 - y1)
        union = aw * ah + bw * bh - inter
        return inter / union if union > 0 else 0.0

    remaining = sorted(dets, key=lambda d: -d["score"])
    out = []
    while remaining:
        best = remaining[0]
        cluster = [d for d in remaining if iou(d["box"], best["box"])
                   > min_suppression_threshold]
        remaining = [d for d in remaining if d not in cluster]
        total = sum(d["score"] for d in cluster)
        box = np.zeros(4)
        kps = np.zeros_like(np.asarray(best["keypoints"]))
        for d in cluster:
            wgt = d["score"] / total
            box += wgt * np.array(d["box"])
            kps += wgt * np.asarray(d["keypoints"])
        merged = dict(best)
        merged["box"] = tuple(box)
        merged["keypoints"] = kps
        out.append(merged)
    return out


def rect_from_face_detection(det, img_w, img_h):
    """DetectionsToRects (kp0 right eye -> kp1 left eye, target 0 deg) +
    RectTransformation(scale 1.5, square_long). rotation follows MediaPipe:
    theta = normalize(target - atan2(-(dy), dx)), y down, CCW-positive in the
    R(theta) = [[c,-s],[s,c]] image-coordinate sense."""
    x, y, w, h = det["box"]
    cx, cy = x + w / 2, y + h / 2
    kp = det["keypoints"]
    dx = (kp[1][0] - kp[0][0]) * img_w
    dy = (kp[1][1] - kp[0][1]) * img_h
    angle = normalize_angle(-math.atan2(-dy, dx))  # target angle 0
    side = max(w * img_w, h * img_h) * 1.5
    return cx * img_w, cy * img_h, side, side, angle


def rect_from_pose_detection(det, img_w, img_h):
    """AlignmentPointsRects (centre kp0, radius |kp1-kp0|, target 90 deg) +
    RectTransformation(scale 1.25, square_long). Same rotation convention as
    rect_from_face_detection."""
    kp = det["keypoints"]
    cx, cy = kp[0][0] * img_w, kp[0][1] * img_h
    dx = kp[1][0] * img_w - cx
    dy = kp[1][1] * img_h - cy
    radius = math.sqrt(dx * dx + dy * dy)
    angle = normalize_angle(math.pi / 2 - math.atan2(-dy, dx))
    side = 2 * radius * 1.25
    return cx, cy, side, side, angle


def normalize_angle(a):
    return a - 2 * math.pi * math.floor((a + math.pi) / (2 * math.pi))


def crop_rotated_rect(img, rect, out_size):
    """Sample the rotated rect (cx,cy,w,h px + MediaPipe rotation) into an
    out_size x out_size RGB uint8 array. Output (u,v) maps to image point
    centre + R(theta) . ((u/out - 0.5) * w, (v/out - 0.5) * h); plain bilinear,
    BORDER_ZERO — MediaPipe's GetRotatedSubRectToRectTransformMatrix."""
    import cv2
    arr = np.asarray(img)
    cx, cy, w, h, angle = rect
    ca, sa = math.cos(angle), math.sin(angle)
    sx, sy = w / out_size, h / out_size
    # input <- output affine, then invert for warpAffine's dst<-src semantics
    m = np.array([
        [ca * sx, -sa * sy, cx - (ca * sx + -sa * sy) * (out_size / 2.0)],
        [sa * sx, ca * sy, cy - (sa * sx + ca * sy) * (out_size / 2.0)],
    ], dtype=np.float64)
    return cv2.warpAffine(arr, m, (out_size, out_size),
                          flags=cv2.INTER_LINEAR | cv2.WARP_INVERSE_MAP,
                          borderMode=cv2.BORDER_CONSTANT, borderValue=0)


def project_landmarks(pts_norm, rect, img_w, img_h):
    """LandmarkProjection: normalized crop coords -> image pixel coords
    (x' = cx + dx*w*cos - dy*h*sin, same R(theta) as the crop)."""
    cx, cy, w, h, angle = rect
    x = pts_norm[:, 0] - 0.5
    y = pts_norm[:, 1] - 0.5
    ca, sa = math.cos(angle), math.sin(angle)
    px = cx + x * w * ca - y * h * sa
    py = cy + x * w * sa + y * h * ca
    out = pts_norm.copy()
    out[:, 0] = px
    out[:, 1] = py
    if out.shape[1] > 2:
        out[:, 2] = pts_norm[:, 2] * w
    return out


def sigmoid(x):
    x = np.clip(x, -100, 100)
    return np.where(x >= 0, 1.0 / (1.0 + np.exp(-x)),
                    np.exp(x) / (1.0 + np.exp(x)))


def umeyama_rotation(src, dst, weights):
    """Weighted Kabsch: rotation R (+ translation) with dst ~= s*R*src + t.
    Returns (R 3x3, t 3, s). Scale solved then discarded by callers that only
    want the pose."""
    w = weights / weights.sum()
    mu_s = (src * w[:, None]).sum(axis=0)
    mu_d = (dst * w[:, None]).sum(axis=0)
    sc = src - mu_s
    dc = dst - mu_d
    cov = (dc * w[:, None]).T @ sc
    U, S, Vt = np.linalg.svd(cov)
    d = np.sign(np.linalg.det(U @ Vt))
    D = np.diag([1.0, 1.0, d])
    R = U @ D @ Vt
    var = (w[:, None] * sc * sc).sum()
    s = (S * [1, 1, d]).sum() / var if var > 0 else 1.0
    t = mu_d - s * (R @ mu_s)
    return R, t, s


# ---------------------------------------------------------------------------
# ONNX pipelines (ours) — mirror of what Slice C does in C++
# ---------------------------------------------------------------------------

class OnnxFacePipeline:
    def __init__(self, out_dir, canonical_obj, procrustes_pbtxt):
        self.det = ort_session(os.path.join(out_dir, "face", "face_detector.onnx"))
        self.lmk = ort_session(os.path.join(out_dir, "face", "face_landmarks.onnx"))
        self.bs = ort_session(os.path.join(out_dir, "face", "face_blendshapes.onnx"))
        self.det_size = self.det.get_inputs()[0].shape[1]
        self.lmk_size = self.lmk.get_inputs()[0].shape[1]
        self.anchors = gen_ssd_anchors(self.det_size, [8, 16, 16, 16])
        assert self.anchors.shape[0] == self.det.get_outputs()[0].shape[1], \
            f"anchor count {self.anchors.shape[0]} != model {self.det.get_outputs()[0].shape[1]}"
        self.canonical = load_canonical_obj(canonical_obj)
        ids, wgt = load_procrustes_basis(procrustes_pbtxt)
        self.basis_ids = ids
        self.basis_w = wgt

    def __call__(self, img):
        from PIL import Image
        img = img.convert("RGB")
        W, H = img.size
        # --- stage 1: detector
        lb, pad = letterbox(img, self.det_size)
        x = lb.astype(np.float32)[None] / 127.5 - 1.0
        raw_box, raw_score = self.det.run(None, {self.det.get_inputs()[0].name: x})
        dets = decode_detections(raw_box[0], raw_score[0], self.anchors,
                                 self.det_size, num_keypoints=6)
        if not dets:
            return None
        det = dets[0]
        det["box"] = tuple(unletterbox_points(
            np.array([[det["box"][0], det["box"][1]],
                      [det["box"][0] + det["box"][2], det["box"][1] + det["box"][3]]]),
            pad).reshape(-1))
        det["box"] = (det["box"][0], det["box"][1],
                      det["box"][2] - det["box"][0], det["box"][3] - det["box"][1])
        det["keypoints"] = unletterbox_points(np.asarray(det["keypoints"]), pad)
        rect = rect_from_face_detection(det, W, H)
        # --- stage 2: landmarks
        crop = crop_rotated_rect(img, rect, self.lmk_size)
        x = crop.astype(np.float32)[None] / 255.0
        outs = self.lmk.run(None, {self.lmk.get_inputs()[0].name: x})
        lmk_raw = outs[0].reshape(-1, 3) / self.lmk_size
        presence = float(sigmoid(outs[1].reshape(-1)[0]))
        pts = project_landmarks(lmk_raw, rect, W, H)  # px
        # --- stage 3: blendshapes (146 subset, pixel coords, 2D)
        sub = pts[BLENDSHAPE_LANDMARK_SUBSET][:, :2].astype(np.float32)
        bs = self.bs.run(None, {self.bs.get_inputs()[0].name: sub[None]})[0]
        bs = bs.reshape(-1)
        # --- head pose: weighted Kabsch canonical(cm) -> camera-ish frame
        pose_pts = np.stack([pts[:468, 0], -pts[:468, 1], -pts[:468, 2]], axis=1)
        weights = np.zeros(468, dtype=np.float64)
        weights[self.basis_ids] = self.basis_w
        R, t, s = umeyama_rotation(self.canonical, pose_pts, weights)
        return {
            "landmarks": pts,            # 478 x 3, px (z in px, w-scaled)
            "presence": presence,
            "blendshapes": bs,           # 52
            "rotation": R,               # canonical -> camera
        }


class OnnxPosePipeline:
    def __init__(self, out_dir):
        self.det = ort_session(os.path.join(out_dir, "pose", "pose_detector.onnx"))
        self.lmk = ort_session(os.path.join(out_dir, "pose", "pose_landmarks.onnx"))
        self.det_size = self.det.get_inputs()[0].shape[1]
        self.lmk_size = self.lmk.get_inputs()[0].shape[1]
        self.anchors = gen_ssd_anchors(self.det_size, [8, 16, 32, 32, 32])
        assert self.anchors.shape[0] == self.det.get_outputs()[0].shape[1]

    def __call__(self, img):
        img = img.convert("RGB")
        W, H = img.size
        lb, pad = letterbox(img, self.det_size)
        x = lb.astype(np.float32)[None] / 127.5 - 1.0
        raw_box, raw_score = self.det.run(None, {self.det.get_inputs()[0].name: x})
        dets = decode_detections(raw_box[0], raw_score[0], self.anchors,
                                 self.det_size, num_keypoints=4)
        if not dets:
            return None
        det = dets[0]
        det["keypoints"] = unletterbox_points(np.asarray(det["keypoints"]), pad)
        rect = rect_from_pose_detection(det, W, H)
        crop = crop_rotated_rect(img, rect, self.lmk_size)
        x = crop.astype(np.float32)[None] / 255.0
        outs = self.lmk.run(None, {self.lmk.get_inputs()[0].name: x})
        raw = outs[0].reshape(-1, 5)  # 39 x (x,y,z,vis,presence)
        # unlike the face model (logit), the pose flag is already a probability
        pose_flag = float(outs[1].reshape(-1)[0])
        world = outs[4].reshape(-1, 3)
        pts_norm = raw[:, :3] / self.lmk_size
        pts = project_landmarks(pts_norm, rect, W, H)
        vis = sigmoid(raw[:, 3])
        # world landmarks: rotate by the rect rotation only (no scale)
        cx, cy, w, h, angle = rect
        ca, sa = math.cos(angle), math.sin(angle)
        wx = world[:, 0] * ca - world[:, 1] * sa
        wy = world[:, 0] * sa + world[:, 1] * ca
        world_rot = np.stack([wx, wy, world[:, 2]], axis=1)
        return {
            "landmarks": pts[:33],
            "visibility": vis[:33],
            "world": world_rot[:33],
            "presence": pose_flag,
        }


def load_canonical_obj(path):
    """468 canonical face model vertices (cm), mediapipe face_geometry data."""
    verts = []
    with open(path) as f:
        for line in f:
            if line.startswith("v "):
                verts.append([float(v) for v in line.split()[1:4]])
    v = np.array(verts, dtype=np.float64)
    assert v.shape == (468, 3), v.shape
    return v


def load_procrustes_basis(path):
    ids, weights = [], []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("procrustes_landmark_basis"):
                parts = line.replace("{", " ").replace("}", " ").split()
                ids.append(int(parts[parts.index("landmark_id:") + 1]))
                weights.append(float(parts[parts.index("weight:") + 1]))
    return np.array(ids), np.array(weights, dtype=np.float64)


# ---------------------------------------------------------------------------
# parity vs the python mediapipe reference
# ---------------------------------------------------------------------------

def run_face_parity(face_task, out_dir, images, canonical_obj, procrustes_pbtxt):
    import mediapipe as mp
    from mediapipe.tasks import python as mp_python
    from mediapipe.tasks.python import vision as mp_vision
    from PIL import Image

    ours = OnnxFacePipeline(out_dir, canonical_obj, procrustes_pbtxt)
    options = mp_vision.FaceLandmarkerOptions(
        base_options=mp_python.BaseOptions(model_asset_path=face_task),
        output_face_blendshapes=True,
        output_facial_transformation_matrixes=True,
        num_faces=1)
    ref = mp_vision.FaceLandmarker.create_from_options(options)

    print("\n== FACE PARITY (ONNX pipeline vs python mediapipe) ==")
    worst_bs, worst_px, worst_deg = 0.0, 0.0, 0.0
    n_ok = 0
    n_mismatch = 0
    for path in images:
        img = Image.open(path)
        mp_img = mp.Image(image_format=mp.ImageFormat.SRGB,
                          data=np.asarray(img.convert("RGB")))
        res = ref.detect(mp_img)
        mine = ours(img)
        # Detection DISAGREEMENTS are parity failures, not skips: if we only
        # require n_ok > 0, one matching image can hide mismatches on every
        # other asset. Count them and assert none remain at the end.
        if not res.face_landmarks:
            if mine is not None:
                print(f"  {os.path.basename(path)}: MISMATCH — reference found "
                      f"no face, we did")
                n_mismatch += 1
            else:
                print(f"  {os.path.basename(path)}: no face (both agree)")
            continue
        if mine is None:
            print(f"  {os.path.basename(path)}: MISMATCH — reference found a "
                  f"face, we did NOT")
            n_mismatch += 1
            continue
        W, H = img.size
        ref_pts = np.array([[pt.x * W, pt.y * H] for pt in res.face_landmarks[0]])
        d_px = np.linalg.norm(ref_pts - mine["landmarks"][:, :2], axis=1)
        ref_bs = np.array([b.score for b in res.face_blendshapes[0]])
        d_bs = np.abs(ref_bs - mine["blendshapes"])
        deg = np.nan
        if res.facial_transformation_matrixes:
            Rref = np.array(res.facial_transformation_matrixes[0])[:3, :3]
            # our R maps canonical -> camera, so compare directly
            dR = Rref.T @ mine["rotation"]
            deg = math.degrees(math.acos(np.clip((np.trace(dR) - 1) / 2, -1, 1)))
        print(f"  {os.path.basename(path)}: landmarks mean {d_px.mean():.2f}px "
              f"max {d_px.max():.2f}px | blendshapes mean {d_bs.mean():.4f} "
              f"max {d_bs.max():.4f} | head-pose delta {deg:.2f} deg "
              f"| presence {mine['presence']:.3f}")
        worst_bs = max(worst_bs, d_bs.max())
        worst_px = max(worst_px, d_px.max())
        if not math.isnan(deg):
            worst_deg = max(worst_deg, deg)
        n_ok += 1
    ref.close()
    assert n_ok > 0, "no face image produced a reference result"
    assert n_mismatch == 0, (
        f"{n_mismatch} image(s) disagreed on face detection — parity FAILED")
    print(f"  WORST: blendshapes {worst_bs:.4f} (target <= 0.02), "
          f"landmarks {worst_px:.2f}px (target <= 2px on the tracked face), "
          f"head-pose {worst_deg:.2f} deg (informational)")
    return {"worst_blendshape_abs": worst_bs, "worst_landmark_px": worst_px,
            "worst_headpose_deg": worst_deg, "images": n_ok}


def run_pose_parity(pose_task, out_dir, images):
    import mediapipe as mp
    from mediapipe.tasks import python as mp_python
    from mediapipe.tasks.python import vision as mp_vision
    from PIL import Image

    ours = OnnxPosePipeline(out_dir)
    options = mp_vision.PoseLandmarkerOptions(
        base_options=mp_python.BaseOptions(model_asset_path=pose_task),
        num_poses=1)
    ref = mp_vision.PoseLandmarker.create_from_options(options)

    print("\n== POSE PARITY (ONNX pipeline vs python mediapipe) ==")
    worst_world = 0.0
    n_ok = 0
    for path in images:
        img = Image.open(path)
        mp_img = mp.Image(image_format=mp.ImageFormat.SRGB,
                          data=np.asarray(img.convert("RGB")))
        res = ref.detect(mp_img)
        mine = ours(img)
        if not res.pose_world_landmarks:
            print(f"  {os.path.basename(path)}: no pose (reference)")
            continue
        if mine is None:
            print(f"  {os.path.basename(path)}: REFERENCE found a pose, we did NOT")
            continue
        ref_world = np.array([[pt.x, pt.y, pt.z]
                              for pt in res.pose_world_landmarks[0]])
        d = np.linalg.norm(ref_world - mine["world"], axis=1)
        print(f"  {os.path.basename(path)}: world landmarks mean "
              f"{d.mean() * 100:.2f}cm max {d.max() * 100:.2f}cm "
              f"| presence {mine['presence']:.3f}")
        worst_world = max(worst_world, d.max())
        n_ok += 1
    ref.close()
    assert n_ok > 0, "no pose image produced a reference result"
    print(f"  WORST: world {worst_world * 100:.2f}cm (target <= 2cm)")
    return {"worst_world_m": worst_world, "images": n_ok}


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def extract_task(task_path, dest):
    os.makedirs(dest, exist_ok=True)
    with zipfile.ZipFile(task_path) as z:
        z.extractall(dest)
    return {os.path.splitext(n)[0]: os.path.join(dest, n)
            for n in os.listdir(dest) if n.endswith(".tflite")}


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--face-task", help="face_landmarker.task path")
    ap.add_argument("--pose-task", help="pose_landmarker_full.task path")
    ap.add_argument("--images", required=True,
                    help="dir with test images (face parity uses images whose "
                         "name doesn't start with 'pose', pose parity the rest)")
    ap.add_argument("--out-dir", default=".mocap_work/out")
    ap.add_argument("--canonical-obj", default=".mocap_work/canonical_face_model.obj")
    ap.add_argument("--procrustes", default=".mocap_work/geometry_pipeline_metadata_landmarks.pbtxt")
    ap.add_argument("--verify-only", action="store_true",
                    help="skip conversion, only run parity on existing out-dir")
    args = ap.parse_args()

    imgs = sorted(os.path.join(args.images, f) for f in os.listdir(args.images)
                  if f.lower().endswith((".jpg", ".jpeg", ".png")))
    face_imgs = [p for p in imgs if not os.path.basename(p).startswith("pose")]
    pose_imgs = [p for p in imgs if os.path.basename(p).startswith("pose")]

    report = {}
    if args.face_task:
        face_out = os.path.join(args.out_dir, "face")
        os.makedirs(face_out, exist_ok=True)
        if not args.verify_only:
            print("== converting face models ==")
            tflites = extract_task(args.face_task, os.path.join(args.out_dir, "_face_tflite"))
            convert_with_fallback(tflites["face_detector"],
                                  os.path.join(face_out, "face_detector.onnx"))
            convert_with_fallback(tflites["face_landmarks_detector"],
                                  os.path.join(face_out, "face_landmarks.onnx"))
            convert_with_fallback(tflites["face_blendshapes"],
                                  os.path.join(face_out, "face_blendshapes.onnx"))
        report["face"] = run_face_parity(args.face_task, args.out_dir, face_imgs,
                                         args.canonical_obj, args.procrustes)
        assert report["face"]["worst_blendshape_abs"] <= 0.02, "blendshape parity FAILED"
        # The documented contract advertises a 2px landmark target; enforce it
        # so parity can't silently regress while the script prints success.
        assert report["face"]["worst_landmark_px"] <= 2.0, (
            f"landmark parity FAILED "
            f"({report['face']['worst_landmark_px']:.2f}px > 2px)")

    if args.pose_task:
        pose_out = os.path.join(args.out_dir, "pose")
        os.makedirs(pose_out, exist_ok=True)
        if not args.verify_only:
            print("== converting pose models ==")
            tflites = extract_task(args.pose_task, os.path.join(args.out_dir, "_pose_tflite"))
            convert_with_fallback(tflites["pose_detector"],
                                  os.path.join(pose_out, "pose_detector.onnx"))
            convert_with_fallback(tflites["pose_landmarks_detector"],
                                  os.path.join(pose_out, "pose_landmarks.onnx"))
        report["pose"] = run_pose_parity(args.pose_task, args.out_dir, pose_imgs)
        assert report["pose"]["worst_world_m"] <= 0.02, "pose world parity FAILED"

    # contract dump for the C++ side / spike doc
    contract = {
        "blendshape_names": BLENDSHAPE_NAMES,
        "blendshape_landmark_subset": BLENDSHAPE_LANDMARK_SUBSET,
        "pose_landmark_names": POSE_LANDMARK_NAMES,
        "face_detector": {"input": 128, "range": [-1, 1],
                          "anchors": {"strides": [8, 16, 16, 16], "count": 896},
                          "keypoints": ["right_eye", "left_eye", "nose", "mouth",
                                        "right_ear", "left_ear"],
                          "roi": {"rotation_kp": [0, 1], "target_angle_deg": 0,
                                  "scale": 1.5, "square_long": True}},
        "face_landmarks": {"input": 256, "range": [0, 1],
                           "outputs": "1434=478*xyz in 256-space; presence logit"},
        "face_blendshapes": {"input": "[1,146,2] (x*W, y*H) px", "output": 52},
        "pose_detector": {"input": 224, "range": [-1, 1],
                          "anchors": {"strides": [8, 16, 32, 32, 32], "count": 2254},
                          "roi": {"center_kp": 0, "radius_kp": 1,
                                  "target_angle_deg": 90, "scale": 1.25}},
        "pose_landmarks": {"input": 256, "range": [0, 1],
                           "outputs": "195=39*(x,y,z,vis,presence); world 117=39*xyz metres"},
        "parity": report,
    }
    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "mocap_contract.json"), "w") as f:
        json.dump(contract, f, indent=2)
    print(f"\ncontract + parity report -> {os.path.join(args.out_dir, 'mocap_contract.json')}")
    print("ALL PARITY CHECKS PASSED")


if __name__ == "__main__":
    sys.exit(main())
