name: Test Intel Mac Runner

on: 
  workflow_dispatch  # Manual trigger for testing
  
jobs:
  test-intel-runner:
    runs-on: [self-hosted, macos-intel]
    steps:
    - name: Test Intel Mac Runner
      run: |
        echo "=== Intel Mac Runner Test ==="
        echo "Architecture: $(uname -m)"
        echo "Expected: x86_64"
        echo ""
        echo "macOS version: $(sw_vers -productVersion)"
        echo "Hardware info: $(system_profiler SPHardwareDataType | grep "Processor Name")"
        echo "Available CPU cores: $(sysctl -n hw.ncpu)"
        echo ""
        echo "Runner labels: self-hosted, macOS, X64, macos-intel"
        echo ""
        echo "Development tools:"
        echo "Xcode: $(xcode-select --version)"
        echo "Git: $(git --version)"
        echo "CMake: $(cmake --version | head -1)"
        echo ""
        echo "✅ Intel Mac runner is working correctly!"
        
    - name: Test checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Verify repository access
      run: |
        echo "Repository contents:"
        ls -la
        echo ""
        echo "CMakeLists.txt exists: $([ -f CMakeLists.txt ] && echo "✅ Yes" || echo "❌ No")"
        echo "src directory exists: $([ -d src ] && echo "✅ Yes" || echo "❌ No")"
        echo ""
        echo "✅ Repository access working correctly!" 