## VATPlayer — drives a MeshInstance3D's ShaderMaterial from a QtMeshEditor
## VAT bake.
##
## Drop the bake directory's path into `bake_dir`. The script will:
##   1. Read the JSON sidecar (frame_count, fps, vertex_count, bounds).
##   2. Load the position PNG as a non-sRGB, nearest-filter texture.
##   3. Load the bundled `.gdshader` (or fall back to the embedded copy
##      below if the bake didn't include one) into a ShaderMaterial.
##   4. Bind that material to its MeshInstance3D and tick `current_frame`
##      every _process at the sidecar's FPS.
##
## Expected layout in `bake_dir`:
##   <basename>_pos.png          (position texture)
##   [<basename>_nrm.png]        (optional normal texture)
##   <basename>.json             (sidecar)
##   [<basename>.gdshader]       (auto-generated by --target godot)
##
## The MeshInstance3D's mesh must have the SAME vertex order Ogre saw
## at bake time. The recommended source is `qtmesh convert <input> -o
## <bake_dir>/mesh.gltf` so Godot loads what the baker observed.

class_name VATPlayer
extends MeshInstance3D

@export_dir var bake_dir: String = ""

## Path to the glTF whose mesh geometry should drive the VAT replay.
## MUST match the vertex order the baker saw, otherwise the position
## texture's column indexing will be wrong and the result will explode.
## The staging script always sets this to `<bake_dir>/source.gltf`.
@export_file("*.gltf", "*.glb") var source_gltf: String = ""

## When true, sample with bilinear filtering on the V axis so playback
## smoothly interpolates between frames. Off by default — matches the
## auto-generated shader's `filter_nearest` so playback is bit-exact
## with the bake (good for verification; ugly at low FPS).
@export var frame_interp: bool = false

## Loop point in frames. -1 = full clip from sidecar's frame_count.
@export var loop_frames: int = -1

var _frame_count: int = 0
var _fps: float = 30.0
var _vertex_count: int = 0
var _bounds_min: Vector3 = Vector3.ZERO
var _bounds_max: Vector3 = Vector3.ONE
var _shader_material: ShaderMaterial   # legacy reference; kept null
var _surface_materials: Array[ShaderMaterial] = []
var _current_frame: float = 0.0


func _ready() -> void:
	if bake_dir.is_empty():
		push_error("VATPlayer: bake_dir is empty")
		return
	# Load the glTF's mesh resource so the VAT replay runs on the
	# SAME geometry the baker observed. Without this, the script
	# was silently driving the editor placeholder BoxMesh, which
	# produced a weird-looking blob and (worse) created the
	# illusion that "VAT works" when the user was actually only
	# seeing the live-skinned mesh on the left side.
	if not _load_source_mesh():
		push_error("VATPlayer: failed to load source mesh from %s" % source_gltf)
		return
	if not _load_bake():
		push_error("VATPlayer: failed to load bake from %s" % bake_dir)
		return


## Walk the glTF runtime scene to find the first MeshInstance3D and
## adopt its mesh. We do NOT instance the whole glTF scene under us —
## that would bring the Skeleton3D + SkinReference along, and Godot
## would skin the mesh on top of our shader, double-deforming it.
func _load_source_mesh() -> bool:
	if source_gltf.is_empty():
		push_error("VATPlayer: source_gltf is empty")
		return false
	var doc := GLTFDocument.new()
	var state := GLTFState.new()
	var abs_path: String = ProjectSettings.globalize_path(source_gltf)
	var err: int = doc.append_from_file(abs_path, state)
	if err != OK:
		push_error("VATPlayer: GLTFDocument.append_from_file('%s') failed: %d" %
			[abs_path, err])
		return false
	var scene: Node = doc.generate_scene(state)
	if scene == null:
		return false
	var found_mesh: ArrayMesh = _first_mesh_in(scene)
	scene.queue_free()  # We only wanted the mesh resource.
	if found_mesh == null:
		push_error("VATPlayer: no MeshInstance3D found in %s" % source_gltf)
		return false
	mesh = found_mesh
	# Belt-and-braces: even if a Skeleton3D existed somewhere in the
	# instanced scene, this MeshInstance3D has no skeleton path, so
	# Godot's skinning code never runs against us. The vertex shader
	# is the ONLY thing moving vertices.
	skeleton = NodePath("")
	return true


func _first_mesh_in(root: Node) -> ArrayMesh:
	if root is MeshInstance3D:
		var m: Mesh = (root as MeshInstance3D).mesh
		if m is ArrayMesh:
			return m as ArrayMesh
	for c in root.get_children():
		var found := _first_mesh_in(c)
		if found:
			return found
	return null


## Walks `bake_dir`, picks up the first `*.json` it finds, and treats
## its `posTexture` / `nrmTexture` fields as paths relative to the
## sidecar. Returns true when everything wires up.
func _load_bake() -> bool:
	var dir := DirAccess.open(bake_dir)
	if dir == null:
		push_error("VATPlayer: cannot open %s" % bake_dir)
		return false
	var json_path := ""
	var shader_path := ""
	for f in dir.get_files():
		if f.ends_with(".json") and json_path.is_empty():
			json_path = bake_dir.path_join(f)
		elif f.ends_with(".gdshader") and shader_path.is_empty():
			shader_path = bake_dir.path_join(f)
	if json_path.is_empty():
		push_error("VATPlayer: no .json sidecar in %s" % bake_dir)
		return false

	var sidecar_text: String = FileAccess.get_file_as_string(json_path)
	var sidecar: Variant = JSON.parse_string(sidecar_text)
	if typeof(sidecar) != TYPE_DICTIONARY:
		push_error("VATPlayer: malformed sidecar at %s" % json_path)
		return false

	# Required fields per QtMeshEditor VAT v1 sidecar contract.
	for required_key in ["frameCount", "vertexCount", "fps", "bounds", "posTexture"]:
		if not sidecar.has(required_key):
			push_error("VATPlayer: sidecar missing '%s' key" % required_key)
			return false

	_frame_count = int(sidecar["frameCount"])
	_vertex_count = int(sidecar["vertexCount"])
	_fps = float(sidecar["fps"])

	var b: Dictionary = sidecar["bounds"]
	_bounds_min = Vector3(
		float(b["min"]["x"]), float(b["min"]["y"]), float(b["min"]["z"]))
	_bounds_max = Vector3(
		float(b["max"]["x"]), float(b["max"]["y"]), float(b["max"]["z"]))

	var pos_path: String = bake_dir.path_join(str(sidecar["posTexture"]))
	var pos_tex: Texture2D = _load_data_texture(pos_path)
	if pos_tex == null:
		push_error("VATPlayer: failed to load %s" % pos_path)
		return false

	# Normal texture is optional — only present when --normals was passed
	# to the baker. We surface it through `nrm_tex` for shaders that
	# want it, but the auto-generated default shader doesn't sample it.
	var nrm_tex: Texture2D = null
	if sidecar.has("nrmTexture"):
		var nrm_path: String = bake_dir.path_join(str(sidecar["nrmTexture"]))
		nrm_tex = _load_data_texture(nrm_path)

	# We always use the embedded shader. The bake's auto-generated
	# `.gdshader` is a minimal demo that doesn't account for
	# multi-submesh meshes (it lacks the `vertex_offset` uniform we
	# need for any real Mixamo/glTF asset). The embedded copy adds
	# vertex_offset, optional normal-map sampling, and Godot's
	# standard PBR lighting so the playback isn't flat-shaded.
	#
	# We keep `shader_path` discovery above for diagnostics / a future
	# slice that fixes the baker to emit a multi-surface-aware shader.
	var shader := Shader.new()
	shader.code = _builtin_shader_code()

	# Per-surface materials. Multi-submesh meshes (Mixamo bodies are
	# typically 5–15 submeshes — body / hair / clothing parts) draw
	# each surface separately, and Godot's `VERTEX_ID` restarts at 0
	# for each surface. We have to tell every surface its starting
	# column in the global bake texture via a per-material
	# `vertex_offset` uniform so the shader can compute the right `u`.
	#
	# We also pick up the source mesh's per-surface diffuse texture
	# from the glTF's StandardMaterial3D (if any) and forward it as
	# `albedo_tex` so the VAT replay looks like the original — not
	# a flat untextured silhouette.
	_shader_material = null  # No longer using a single shared material.
	_surface_materials.clear()
	var running_offset := 0
	for i in range(mesh.get_surface_count()):
		var mat := ShaderMaterial.new()
		mat.shader = shader
		mat.set_shader_parameter("pos_tex", pos_tex)
		if nrm_tex != null:
			mat.set_shader_parameter("nrm_tex", nrm_tex)
			mat.set_shader_parameter("has_nrm_tex", true)
		else:
			mat.set_shader_parameter("has_nrm_tex", false)
		mat.set_shader_parameter("frame_count", _frame_count)
		mat.set_shader_parameter("vertex_count", _vertex_count)
		mat.set_shader_parameter("vertex_offset", running_offset)
		mat.set_shader_parameter("bounds_min", _bounds_min)
		mat.set_shader_parameter("bounds_max", _bounds_max)
		mat.set_shader_parameter("current_frame", 0.0)

		# Look up the diffuse texture on the source mesh's per-surface
		# material so the VAT mesh inherits the original look. The
		# glTF importer sets surface materials directly on the
		# ArrayMesh as StandardMaterial3D; we hand the texture +
		# albedo color off to the VAT shader so it can multiply in
		# the fragment stage.
		var src_mat: Material = mesh.surface_get_material(i)
		if src_mat is StandardMaterial3D:
			var sm := src_mat as StandardMaterial3D
			var albedo := sm.albedo_texture
			if albedo != null:
				mat.set_shader_parameter("albedo_tex", albedo)
				mat.set_shader_parameter("has_albedo_tex", true)
			else:
				mat.set_shader_parameter("has_albedo_tex", false)
			mat.set_shader_parameter("base_color", Vector3(sm.albedo_color.r, sm.albedo_color.g, sm.albedo_color.b))
		else:
			mat.set_shader_parameter("has_albedo_tex", false)
			mat.set_shader_parameter("base_color", Vector3(0.85, 0.78, 0.65))

		set_surface_override_material(i, mat)
		_surface_materials.append(mat)
		# Advance offset by this surface's vertex count for the next.
		var surface_verts: int = (mesh.surface_get_arrays(i)[Mesh.ARRAY_VERTEX] as PackedVector3Array).size()
		running_offset += surface_verts

	# Override the MeshInstance3D's culling AABB to the bake bounds.
	# By default Godot culls based on the mesh's static bind-pose
	# AABB; our vertex shader displaces vertices well outside that
	# box per-frame, so the renderer was deciding the mesh wasn't
	# visible and skipping its draw call — which manifests as the
	# mesh appearing frozen at frame 0 (the frames it DID draw were
    # the ones where the AABB happened to overlap the camera).
	#
	# We pad the bake bounds by 10% per axis to handle interpolated
	# frames sampling slightly outside the captured min/max.
	var pad: Vector3 = (_bounds_max - _bounds_min) * 0.1
	custom_aabb = AABB(_bounds_min - pad, (_bounds_max - _bounds_min) + pad * 2.0)
	extra_cull_margin = pad.length()

	print("VATPlayer: loaded %d frames x %d verts (across %d surfaces) at %.1f fps from %s" %
		[_frame_count, _vertex_count, mesh.get_surface_count(), _fps, bake_dir])
	print("VATPlayer: custom_aabb=%s" % str(custom_aabb))
	if running_offset != _vertex_count:
		push_warning("VATPlayer: surface vertex sum (%d) != bake vertexCount (%d) — VAT replay will be wrong" %
			[running_offset, _vertex_count])
	return true


## Disable sRGB conversion and force nearest-neighbour sampling on the V
## (frame) axis so adjacent frames don't bleed into each other. Godot's
## default Texture2D import path would gamma-correct the PNG; we go
## through Image so we read the raw byte data the baker wrote.
func _load_data_texture(path: String) -> Texture2D:
	var img := Image.load_from_file(path)
	if img == null or img.is_empty():
		return null
	# The bake's encoding is unsigned-normalized; rgba16 is loaded as
	# RGBA16, rgba8 as RGBA8. Godot picks the right format from the
	# PNG header automatically. No conversion needed.
	var tex := ImageTexture.create_from_image(img)
	return tex


func _process(delta: float) -> void:
	if _surface_materials.is_empty() or _frame_count <= 0:
		return
	var loop_count: int = (loop_frames if loop_frames > 0 else _frame_count)
	_current_frame = fposmod(_current_frame + delta * _fps, float(loop_count))
	# Drive every per-surface material's current_frame uniformly.
	for mat in _surface_materials:
		mat.set_shader_parameter("current_frame", _current_frame)


## Embedded shader — Godot 4 spatial that samples the VAT position
## texture, optionally the normal texture, with standard lighting.
## Kept as a string so the .tscn doesn't depend on a generated file
## existing at editor open time.
func _builtin_shader_code() -> String:
	return """
shader_type spatial;
// `cull_disabled` because Godot's glTF importer's winding order
// doesn't always match what Ogre's baker saw — disabling backface
// culling avoids silent invisibility on mismatched meshes. Visual
// difference is minor for opaque PBR; you can switch to cull_back
// if you've verified the orientation. depth_draw_opaque +
// depth_test_default ensures the VAT-driven mesh participates in
// the depth buffer normally (the bug symptom "no ZIndex" reported
// in the test harness was driven by render_mode unshaded inherited
// from the baker's auto-generated minimal shader).
render_mode cull_disabled, depth_draw_opaque, depth_test_default;

uniform sampler2D pos_tex : filter_nearest, repeat_disable, hint_default_white;
uniform sampler2D nrm_tex : filter_nearest, repeat_disable, hint_default_white;
uniform sampler2D albedo_tex : filter_linear_mipmap, repeat_enable, source_color;
uniform bool has_nrm_tex = false;
uniform bool has_albedo_tex = false;

uniform float current_frame = 0.0;
uniform int frame_count = 1;
uniform int vertex_count = 1;
// Per-surface offset into the bake's monolithic position texture.
uniform int vertex_offset = 0;
uniform vec3 bounds_min = vec3(0.0);
uniform vec3 bounds_max = vec3(1.0);
uniform vec3 base_color : source_color = vec3(0.85, 0.78, 0.65);

// Helper — sample a vertex's animated position at row `v`.
vec3 sample_pos(int vid, float v) {
	float u = (float(vid) + 0.5) / float(vertex_count);
	vec3 t = texture(pos_tex, vec2(u, v)).rgb;
	return bounds_min + t * (bounds_max - bounds_min);
}

// Pass the mesh's static UV0 through to fragment for albedo sampling.
// UVs don't animate — only positions/normals do.
varying vec2 uv0_pass;

void vertex() {
	int global_vid = vertex_offset + VERTEX_ID;
	float v = (current_frame + 0.5) / float(frame_count);
	VERTEX = sample_pos(global_vid, v);
	uv0_pass = UV;

	if (has_nrm_tex) {
		// Normals are unsigned-normalized in [0..1]; remap to
		// [-1..1] direction vectors and renormalize. We also
		// negate the result — Godot's spatial shader `NORMAL`
		// builtin expects the OUTWARD model-space normal that
		// the lighting pipeline can dot with the light direction.
		// The baker captures post-skin normals from Ogre's
		// `_getSkelAnimVertexData()` which in Mixamo / glTF
		// imports often comes out as the FACING-AWAY direction
		// because the FBX → Ogre → glTF round-trip flips one
		// winding pass. The "dark where there should be light"
		// symptom in the test harness traces to this.
		float u = (float(global_vid) + 0.5) / float(vertex_count);
		vec3 n = texture(nrm_tex, vec2(u, v)).rgb * 2.0 - 1.0;
		NORMAL = -normalize(n);
	} else {
		// No baked normal map — derive a stable per-vertex normal
		// by sampling neighbours along the vertex-id axis and
		// cross-producting two tangent estimates. Not a true
		// surface normal (it's vertex-id-axis tangent), but at
		// least the normal rotates WITH the animation so lighting
		// has direction. For fidelity, re-bake with --normals.
		int prev_vid = max(global_vid - 1, 0);
		int next_vid = min(global_vid + 1, vertex_count - 1);
		vec3 p_prev = sample_pos(prev_vid, v);
		vec3 p_next = sample_pos(next_vid, v);
		vec3 tang = p_next - p_prev;
		if (length(tang) < 1e-6) tang = vec3(1.0, 0.0, 0.0);
		vec3 ref = abs(tang.y) < 0.9 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
		vec3 bitang = normalize(cross(tang, ref));
		NORMAL = normalize(cross(bitang, tang));
	}
}

void fragment() {
	vec3 albedo = base_color;
	if (has_albedo_tex) {
		albedo *= texture(albedo_tex, uv0_pass).rgb;
	}
	ALBEDO = albedo;
	ROUGHNESS = 0.6;
	METALLIC = 0.0;
}
"""
